CREATE DATABASE MAKANANINDO;

-- TABEL 1: DATA MAKANAN KHAS INDONESIA
CREATE TABLE MAKANAN_KHAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAMA_MAKANAN VARCHAR(100) NOT NULL,
    ASAL_DAERAH VARCHAR(100) NOT NULL,
    JENIS_MAKANAN VARCHAR(50) NOT NULL,      -- CONTOH: MAKANAN BERAT, CEMILAN, MINUMAN
    TINGKAT_KEPEDASAN VARCHAR(20) NOT NULL,  -- CONTOH: TIDAK PEDAS, SEDANG, PEDAS
    HARGA_ESTIMASI INT NOT NULL              -- DALAM RUPIAH
);

-- TABEL 2: DATA BAHAN UTAMA KULINER NUSANTARA
CREATE TABLE BAHAN_UTAMA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAMA_BAHAN VARCHAR(100) NOT NULL,
    KATEGORI VARCHAR(50) NOT NULL,       -- CONTOH: REMPAH, PROTEIN, SAYURAN
    DAERAH_PENGHASIL VARCHAR(100) NOT NULL,
    MUSIM_PANEN VARCHAR(50) NOT NULL,
    HARGA_PER_KG INT NOT NULL            -- DALAM RUPIAH
);


INSERT INTO MAKANAN_KHAS (NAMA_MAKANAN, ASAL_DAERAH, JENIS_MAKANAN, TINGKAT_KEPEDASAN, HARGA_ESTIMASI)
VALUES 
('RENDANG', 'SUMATERA BARAT', 'MAKANAN BERAT', 'PEDAS', 35000),
('GUDEG', 'YOGYAKARTA', 'MAKANAN BERAT', 'TIDAK PEDAS', 25000),
('PEMPEK', 'PALEMBANG', 'CEMILAN', 'SEDANG', 20000);

INSERT INTO BAHAN_UTAMA (NAMA_BAHAN, KATEGORI, DAERAH_PENGHASIL, MUSIM_PANEN, HARGA_PER_KG)
VALUES 
('CABAI MERAH', 'REMPAH', 'JAWA BARAT', 'SEPANJANG TAHUN', 40000),
('KELAPA', 'SAYURAN/BUAH', 'SULAWESI', 'SEPANJANG TAHUN', 8000),
('IKAN TENGGIRI', 'PROTEIN', 'SUMATERA SELATAN', 'MUSIM KEMARAU', 60000);






